---
name: Linting json and yaml

on: push

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        working-directory: ./tests
        run: yamllint -c yamllint_sensudocs.yml content  
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Lint JSON files
        working-directory: ./tests
        run: python json-validator.py --directory ../content --extension .md